name: examenmobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12

  # Firebase
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  # Connectivity & Animations
  connectivity_plus: ^5.0.1
  lottie: ^3.3.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.0

  # State Management & Local Storage
  get: ^4.6.5
  get_storage: ^2.1.1

  # Others
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/reviews/