// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fg9lytzrwUNWv0Fk-l1BVz6QLcEsm_c',
    appId: '1:144481283414:web:be32222141daa6d8c4faf7',
    messagingSenderId: '144481283414',
    projectId: 'pro-equinox-381716',
    authDomain: 'pro-equinox-381716.firebaseapp.com',
    storageBucket: 'pro-equinox-381716.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVNab-T3-3XjwFiFV2hoW-PZhcvOO8rYs',
    appId: '1:144481283414:android:bfb57d0e102a881ac4faf7',
    messagingSenderId: '144481283414',
    projectId: 'pro-equinox-381716',
    storageBucket: 'pro-equinox-381716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOEuKDSVYx84U7wm3C6_i-ekOgjXgT69E',
    appId: '1:144481283414:ios:972477dad74fb41ac4faf7',
    messagingSenderId: '144481283414',
    projectId: 'pro-equinox-381716',
    storageBucket: 'pro-equinox-381716.firebasestorage.app',
    androidClientId: '144481283414-kves556fmca19t8tids8a21bsi83f964.apps.googleusercontent.com',
    iosClientId: '144481283414-s1j780s8ub7tflm03pgv0s1q2qiucpmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOEuKDSVYx84U7wm3C6_i-ekOgjXgT69E',
    appId: '1:144481283414:ios:972477dad74fb41ac4faf7',
    messagingSenderId: '144481283414',
    projectId: 'pro-equinox-381716',
    storageBucket: 'pro-equinox-381716.firebasestorage.app',
    androidClientId: '144481283414-kves556fmca19t8tids8a21bsi83f964.apps.googleusercontent.com',
    iosClientId: '144481283414-s1j780s8ub7tflm03pgv0s1q2qiucpmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8fg9lytzrwUNWv0Fk-l1BVz6QLcEsm_c',
    appId: '1:144481283414:web:eb8da4ef3c894b05c4faf7',
    messagingSenderId: '144481283414',
    projectId: 'pro-equinox-381716',
    authDomain: 'pro-equinox-381716.firebaseapp.com',
    storageBucket: 'pro-equinox-381716.firebasestorage.app',
  );

}